### PR TITLE
Migrate CHILLED code to `message-ix-buildings`

### PR DESCRIPTION
**Pull request by measrainsey**
The CHILLED (Cooling and Heating gLobaL Energy Demand) model projects changes in energy intensity for residential + commercial building cooling usage due to climate change impacts. 

Currently the CHILLED code exists in the private `cc_ene_dem` repository: https://github.com/iiasa/cc_ene_dem. Because (1) the repository has quite a lot of legacy code due to the climate impacts on buildings work developing through the years and (2) we are preparing a paper for submission, @byersiiasa, @amastrucci, and I decided it would be best to migrate the (relevant) CHILLED code to this repository. By doing so, the CHILLED model should live in this repository as a module that will also be built upon for future work. 

I think it would be best to migrate this code to work in the general packaging ecosystem that we employ, so that this would allow for both ease of development and ease of usage. That is why this PR's branch hangs off of PR #13 (the [`packaging-docs`](https://github.com/iiasa/message-ix-buildings/pull/13) branch). 

However, because (at the moment) the `packaging-docs` branch conflicts with the `main` branch, this `chilled-migration` branch is also conflicting with the `main` branch. From what I gather, a coordinated effort across MESSAGEix-Buildings developers would be needed to get this repository to a state that is without merge conflicts. Until then, I am creating this (draft) PR as a location to store my work and get the process of moving the CHILLED model started. Note that the CHILLED module is for the time being completely separate from the STURM code, so we should not be causing any conflicts to the STURM module or any other module. 

Because CHILLED is completely based in Python, that will allow for relative ease of integration into the packaging ecosystem. However, extensive work within the CHILLED code would be needed to complete the migration, namely:
- Reorganizing code into functions
- Adding documentation
- More I'm probably not thinking of at the moment

### CODE REVIEW

**Comment by glatterf42** [comment]
Hi @measrainsey, I rebased this PR on top of `tmp`, which should become the new `main` soon if I understand correctly. Consequently, I also changed the target of this PR from `packaging-docs` to `tmp`. 

Crucially, there was one merge conflict I couldn't properly resolve: [sturm/model/F02_init_stock_dyn_fut.R](https://github.com/iiasa/message-ix-buildings/pull/14/files#diff-983caacbdb6e1072a3962fc30c9c310871a8c2a81da8ae1ff3f2943d08abfa55)
Both this PR and `tmp` made significant changes to that file and I have no idea how to resolve them (starting with me not speaking R). At the moment, this file is simply the two versions added together: the `tmp` version from line 1 to 384, the version from this PR from 385 to 727. I'm sorry if this is inconvenient, you could still use your local version of this file and the version from `tmp` to diff them against each other properly, but git just showed me the whole file as a single big conflict instead of individual lines.

As an aside, I seem to have some kind of R-linter installed for my VSCode and this is complaining a lot about the version from `tmp`, @Zh-xy. There are trailing whitespaces, too much indentation, unknown global functions, too long lines, "unnecessary comments", etc. You might want to take a look at that.

**Comment by measrainsey** [comment]
> Hi @measrainsey, I rebased this PR on top of `tmp`, which should become the new `main` soon if I understand correctly. Consequently, I also changed the target of this PR from `packaging-docs` to `tmp`.
> 
> Crucially, there was one merge conflict I couldn't properly resolve: [sturm/model/F02_init_stock_dyn_fut.R](https://github.com/iiasa/message-ix-buildings/pull/14/files#diff-983caacbdb6e1072a3962fc30c9c310871a8c2a81da8ae1ff3f2943d08abfa55) Both this PR and `tmp` made significant changes to that file and I have no idea how to resolve them (starting with me not speaking R). At the moment, this file is simply the two versions added together: the `tmp` version from line 1 to 384, the version from this PR from 385 to 727. I'm sorry if this is inconvenient, you could still use your local version of this file and the version from `tmp` to diff them against each other properly, but git just showed me the whole file as a single big conflict instead of individual lines.

Thanks @glatterf42! I don't use or rely on `F02_init_stock_dyn_fut.R` so should not conflict with my work 👍🏼

**Comment by Zh-xy** [comment]
> Hi @measrainsey, I rebased this PR on top of `tmp`, which should become the new `main` soon if I understand correctly. Consequently, I also changed the target of this PR from `packaging-docs` to `tmp`.
> 
> Crucially, there was one merge conflict I couldn't properly resolve: [sturm/model/F02_init_stock_dyn_fut.R](https://github.com/iiasa/message-ix-buildings/pull/14/files#diff-983caacbdb6e1072a3962fc30c9c310871a8c2a81da8ae1ff3f2943d08abfa55) Both this PR and `tmp` made significant changes to that file and I have no idea how to resolve them (starting with me not speaking R). At the moment, this file is simply the two versions added together: the `tmp` version from line 1 to 384, the version from this PR from 385 to 727. I'm sorry if this is inconvenient, you could still use your local version of this file and the version from `tmp` to diff them against each other properly, but git just showed me the whole file as a single big conflict instead of individual lines.
> 
> As an aside, I seem to have some kind of R-linter installed for my VSCode and this is complaining a lot about the version from `tmp`, @Zh-xy. There are trailing whitespaces, too much indentation, unknown global functions, too long lines, "unnecessary comments", etc. You might want to take a look at that.

Hi @glatterf42, thank you for the update and your efforts on rebasing this PR onto `tmp`. Regarding the R-linter warnings in the `tmp` version, it's valuable feedback. They seem to be style-related concerns that might not affect functionality directly, but I agree it'd be good to have a closer look. Is it possible for you to share the list of the warnings you're seeing?

Regarding the merge conflict in `sturm/model/F02_init_stock_dyn_fut.R`, I agree that a closer examination of both versions is necessary to find the best resolution.

Lastly, I understood that it's still to be decided which branch will become the ` main` . If `chilled-migration`  provides a more suitable folder structure and updated CHILLED model code, it might be beneficial to consider it as the main branch.

**Comment by glatterf42** [comment]
Fair warning, this file alone contains 960 linting problem, which you can see listed in [this file](https://github.com/iiasa/message-ix-buildings/files/14918200/r_linting_erros.json). However, I don't know how clear this is. You could instead check out the linter my VSCode is using and run it on the files yourself: it's called [lintr](https://lintr.r-lib.org/index.html). There might be an extension for your favourite editor and there might be some code package that automatically enforces this code style (things like additional or missing whitespace etc are easily fixable in an automatic manner). Researching this quickly might save you a lot of time; unfortunately, since I don't know R, I can't tell you more myself.

The `chilled-migration` branch and associated PR are based on `tmp` at the moment. The idea would be:

1. You merge the PR #15 from `tmp` to `main`, making `tmp` the new `main`
2. You close #13 and delete the `packaging-docs` branch
3. You rebase this PR #14 on top of the new `main` branch, which should work without conflicts
4. You mark this PR as ready for review and merge it
5. You delete the `tmp` and `chilled-migration` branches

**Comment by khaeru** [comment]
Not a full review, only a couple comments occasioned by this PR being raised in today's MESSAGE team meeting:

- If the code has specific resource requirements (e.g. takes 7 hours to run), that should be stated in the docs.
- The directory /chilled/ lacks an \_\_init__.py file.

**Review by Zh-xy — APPROVED** [review]
sturm/model/F02_init_stock_dyn_fut.R needs to be cleaned up. This can be the topic of the new PR in the future

**Pull request merged**
